// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codler
{
    internal sealed partial class Vsix
    {
        public const string Id = "Codler.978ced38-0c90-442a-b6b2-be51c4591b9c";
        public const string Name = "Codler";
        public const string Description = @"Highlights all user-defined methods and their calls in C# files with custom colors and font size.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Avneet Singh";
        public const string Tags = "C#, Visual Studio, Syntax Highlighting, User Methods, Code Readability, VSIX";
        public const bool IsPreview = true;
    }
}
